### ISSUE TITLE
Byakuren Stage Error th135

### ISSUE THREAD

**Issue by IkuTronHD** [brliron/135tk#1]
There is an error in the Byakuren Stage and it is that there are some graphics that it does not detect when I patch with "th135arc.exe" since with "th135arc-alt.exe" it does not start when I start "th135.exe" (game) I have to use the -h with the original to read the paks to me.

https://cdn.discordapp.com/attachments/618118309438816257/714894728457486537/unknown.png

**Comment by brliron** [comment]
This is a known bug. I could never figure out why it happens. The best fix is to never change th135.pak and do all your edits in th135b.pak.
Some ways to use a patched th135b.pak and an original th135.pak include:
- Archives created by th135arc-alt.exe should be readable by the original game, so you can use a patched th135b.pak, the original th135.pak and the original th135.exe.
- I think there is also a version of th135arc that creates archives compatible with the original game somewhere on the MotK patching thread. It should be around the end (at least in the 2nd half), around some messages from Riatre.
- There is also a th135e.exe in the MotK thread that can read both unpatched and patched pak files. I think it's around page 3 or 4? But IIRC it doesn't work well with the latest game versions.

MotK patching thread: https://www.shrinemaiden.org/forum/index.php?topic=14754.0

**Comment by IkuTronHD** [comment]
Thanks for responding to everything and sorry for being heavy in discord.
