### ISSUE TITLE
Repack of th175arc doesn't work

### ISSUE THREAD

**Issue by xitieshiz2** [brliron/135tk#9]
I don't know if there is a hash verification or anything else , but I just replaced a file and the game crush with no reason every time when content of that file should be show up in the game(like this)
![image](https://user-images.githubusercontent.com/75575551/141479506-74b053a7-e563-411c-8dab-5361f8edd21b.png)

**Comment by Yanstory** [comment]
works for me, did you:

* packed as ``data.cga`` instead of ``data.cgb``?
* forget to put files in ``data`` folder and keep file tree?

**Comment by xitieshiz2** [comment]
> works for me, did you:
> 
> * packed as `data.cga` instead of `data.cgb`?
> * forget to put files in `data` folder and keep file tree?

为啥俩中国人要用英语交流啊t（
这个是要打包成data.cgb的吗？但我是解包的data.cga
第二条啥意思，没太看懂，是不能保留文件树？不能吧

**Comment by Yanstory** [comment]
建议别动cga，以原来的cgb解包后文件替换再打包（

**Comment by xitieshiz2** [comment]
> 建议别动cga，以原来的cgb解包后文件替换再打包（

为啥我解包cgb之后看到的文件都是cga里就有的啊，可以的话能讲讲这次的读取原理吗，谢了

**Comment by Yanstory** [comment]
请参考凭依华（但并不完全一致）

**Comment by xitieshiz2** [comment]
> 请参考凭依华（但并不完全一致）

解决了，谢佬

**Comment by ROCO-freedom** [comment]
您要自己制作汉化包吗？

**Comment by xitieshiz2** [comment]
> 您要自己制作汉化包吗？

确实是在这么做，怎么了？

**Comment by ROCO-freedom** [comment]
没什么，这次我们要有至少三个版本的汉化包了。。。

**Comment by xitieshiz2** [comment]
> 没什么，这次我们要有至少三个版本的汉化包了。。。

额，我知道你是thcrap汉化的负责人，我只是因为thcrap对于某些人安装比较麻烦，想弄个打包版而已，做某些贴图我自己也很头疼（x

**Comment by ROCO-freedom** [comment]
？啊，什么负责人。。。我们也是一个小组而已，静态版补丁也在制作计划当中。只不过优先度比thcrap略低。

**Comment by xitieshiz2** [comment]
> ？啊，什么负责人。。。我们也是一个小组而已，静态版补丁也在制作计划当中。只不过优先度比thcrap略低。

那我可以摸了（逃
不过如果你们需要的话，我也可以来帮点忙

**Comment by ROCO-freedom** [comment]
可以啊，您有QQ吗，我加一下。

**Comment by xitieshiz2** [comment]
> 可以啊，您有QQ吗，我加一下。

好的，2188551535
